export { default as BlockHeader } from './block-header';
export { default as Company } from './company';
export { default as ContactUs } from './contact-us';
export { default as Footer } from './footer';
export { default as Header } from './header';
export { default as PopUp } from './pop-up';
export { default as PrivacyPolicy } from './privacy-policy';
export { default as TelegramWidget } from './telegram-widget';
export { default as Terms } from './terms';
export { default as ThanksContainer } from './thanks-container';
export { default as UpButton } from './up-button';
export { default as WhatAreTheTools } from './what-are-the-tools';
export { default as ToolsInterface } from './tools-interface';
export { default as ToolsOptions } from './tools-options';
export { default as About} from './about';
export { default as WhyDoYouNeed} from './why-do-you-need';
export { default as OtherSites} from './other-sites';
export { default as Input } from './input';
export { default as SocialInput } from './input/socialInput';
